2025-07-01 11:45:12,765 - INFO - [logger.py:26] - importdata initialized with file: ..\data	ransactions.csv
2025-07-01 11:45:12,767 - INFO - [logger.py:26] - Data import started successfully.
2025-07-01 11:45:12,767 - INFO - [logger.py:26] - file path : {file_path}
2025-07-01 11:45:12,774 - INFO - [logger.py:26] - Data import failed: [Errno 22] Invalid argument: 'c:\\Users\\navaz\\Desktop\\Data_Analysis_Project_Files\\src\\..\\data\transactions.csv'
2025-07-01 11:45:12,774 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-01 11:45:12,774 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 10:13:20,262 - INFO - [logger.py:26] - importdata initialized with file: ..\data	ransactions.csv
2025-07-02 10:13:20,265 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 10:13:20,265 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 10:13:20,306 - INFO - [logger.py:26] - Data import failed: [Errno 22] Invalid argument: 'c:\\Users\\navaz\\Desktop\\Data_Analysis_Project_Files\\src\\..\\data\transactions.csv'
2025-07-02 10:13:20,306 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 10:13:20,307 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 11:13:10,129 - ERROR - [logger.py:29] - Database connection failed: No module named 'pymysql'
2025-07-02 11:15:06,239 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 11:16:00,964 - INFO - [logger.py:26] - importdata initialized with file: ..\data	ransactions.csv
2025-07-02 11:16:00,964 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 11:16:00,964 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 11:16:00,989 - INFO - [logger.py:26] - Data import failed: [Errno 22] Invalid argument: 'c:\\Users\\navaz\\Desktop\\Data_Analysis_Project_Files\\src\\..\\data\transactions.csv'
2025-07-02 11:16:00,990 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 11:16:00,990 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 11:16:33,814 - INFO - [logger.py:26] - importdata initialized with file: \data	ransactions.csv
2025-07-02 11:16:33,814 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 11:16:33,814 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 11:16:33,828 - INFO - [logger.py:26] - Data import failed: [Errno 22] Invalid argument: 'c:\\data\transactions.csv'
2025-07-02 11:16:33,829 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 11:16:33,829 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 11:16:59,146 - INFO - [logger.py:26] - importdata initialized with file: .\data	ransactions.csv
2025-07-02 11:16:59,146 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 11:16:59,146 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 11:16:59,166 - INFO - [logger.py:26] - Data import failed: [Errno 22] Invalid argument: 'c:\\Users\\navaz\\Desktop\\Data_Analysis_Project_Files\\src\\.\\data\transactions.csv'
2025-07-02 11:16:59,166 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 11:16:59,166 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 15:50:17,944 - INFO - [logger.py:26] - importdata initialized with file: .\data	ransactions.csv
2025-07-02 15:50:17,944 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 15:50:17,944 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 15:50:17,961 - INFO - [logger.py:26] - Data import failed: [Errno 22] Invalid argument: 'c:\\Users\\navaz\\Desktop\\Data_Analysis_Project_Files\\src\\.\\data\transactions.csv'
2025-07-02 15:50:17,961 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 15:50:17,962 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 15:50:33,759 - INFO - [logger.py:26] - importdata initialized with file: \data	ransactions.csv
2025-07-02 15:50:33,760 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 15:50:33,760 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 15:50:33,769 - INFO - [logger.py:26] - Data import failed: [Errno 22] Invalid argument: 'c:\\data\transactions.csv'
2025-07-02 15:50:33,769 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 15:50:33,769 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 15:59:30,523 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-02 15:59:30,523 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 15:59:30,523 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 15:59:30,647 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 15:59:30,647 - INFO - [logger.py:26] - Data import failed: name 'db_config' is not defined
2025-07-02 15:59:30,647 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 15:59:30,647 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 16:00:48,071 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:01:14,884 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-02 16:01:14,884 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 16:01:14,884 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 16:01:14,893 - INFO - [logger.py:26] - Data import failed: name 'db_config' is not defined
2025-07-02 16:01:14,893 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 16:01:14,893 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 16:03:05,099 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-02 16:03:05,099 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 16:03:05,099 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 16:03:05,181 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:03:12,638 - INFO - [logger.py:26] - Data import failed: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'None' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-02 16:03:12,639 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 16:03:12,639 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 16:03:37,227 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-02 16:03:37,227 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 16:03:37,227 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 16:03:37,322 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:03:44,619 - INFO - [logger.py:26] - Data import failed: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'None' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-02 16:03:44,619 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 16:03:44,621 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 16:24:58,291 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:40:07,727 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:40:53,631 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:43:24,569 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:44:17,334 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 16:44:39,844 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 17:14:20,290 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-02 17:14:20,296 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 17:14:20,296 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 17:14:20,381 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 17:14:20,443 - INFO - [logger.py:26] - Data import failed: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '123@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-02 17:14:20,443 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 17:14:20,443 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 20:02:34,234 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-02 20:02:34,234 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 20:02:34,234 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 20:02:34,317 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 20:02:34,367 - INFO - [logger.py:26] - Data import failed: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '123@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-02 20:02:34,371 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 20:02:34,371 - INFO - [logger.py:26] - Main class is called successfully
2025-07-02 20:06:06,489 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-02 20:06:06,490 - INFO - [logger.py:26] - Data import started successfully.
2025-07-02 20:06:06,490 - INFO - [logger.py:26] - file path : {file_path}
2025-07-02 20:06:06,565 - INFO - [logger.py:26] - Database connection successful.
2025-07-02 20:06:06,680 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-02 20:06:06,682 - INFO - [logger.py:26] - Main class is called successfully
2025-07-03 11:02:33,231 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:02:33,336 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:03:55,739 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:03:55,783 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:04:41,306 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:04:41,352 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:09:10,143 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:09:10,195 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:09:41,676 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:09:41,718 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:09:55,987 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:09:56,036 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:10:14,294 - INFO - [logger.py:26] - Database connection successful.
2025-07-03 11:10:14,340 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 10:39:24,207 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-07 10:39:24,207 - INFO - [logger.py:26] - Data import started successfully.
2025-07-07 10:39:24,223 - INFO - [logger.py:26] - file path : {file_path}
2025-07-07 10:39:24,355 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 10:39:24,582 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-07 10:39:24,582 - INFO - [logger.py:26] - Main class is called successfully
2025-07-07 10:41:26,432 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-07 10:41:26,432 - INFO - [logger.py:26] - Data import started successfully.
2025-07-07 10:41:26,432 - INFO - [logger.py:26] - file path : {file_path}
2025-07-07 10:41:26,503 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 10:41:26,556 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-07 10:41:26,556 - INFO - [logger.py:26] - Main class is called successfully
2025-07-07 10:41:34,775 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 10:41:34,854 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 11:54:11,638 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 11:54:54,087 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 11:56:07,183 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 11:57:56,188 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 11:59:11,492 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 12:00:34,739 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 12:00:34,857 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:33:31,049 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:33:43,937 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:34:06,949 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:36:20,637 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:40:17,630 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:40:44,868 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:41:24,662 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:42:10,701 - INFO - [logger.py:26] - Database connection successful.
2025-07-07 18:42:46,197 - INFO - [logger.py:26] - Database connection successful.
2025-07-08 10:03:22,774 - INFO - [logger.py:26] - importdata initialized with file: ../data/transactions.csv
2025-07-08 10:03:22,775 - INFO - [logger.py:26] - Data import started successfully.
2025-07-08 10:03:22,775 - INFO - [logger.py:26] - file path : {file_path}
2025-07-08 10:03:22,856 - INFO - [logger.py:26] - Database connection successful.
2025-07-08 10:03:22,922 - INFO - [logger.py:26] - Filename is passed successfully
2025-07-08 10:03:22,922 - INFO - [logger.py:26] - Main class is called successfully
2025-07-11 21:26:41,301 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:29:55,769 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:30:42,629 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:31:55,911 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:31:57,884 - INFO - [logger.py:26] - Bar diagram created
2025-07-11 21:48:01,090 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:48:08,934 - INFO - [logger.py:26] - Bar diagram created
2025-07-11 21:48:37,581 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:48:44,315 - INFO - [logger.py:26] - Bar diagram created
2025-07-11 21:49:33,115 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:49:53,300 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:51:35,973 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:55:05,714 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:55:21,518 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 21:56:37,120 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 22:00:56,364 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 22:01:15,711 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 22:01:31,562 - INFO - [logger.py:26] - Bar diagram created
2025-07-11 22:01:51,050 - INFO - [logger.py:26] - Visualize initialized
2025-07-11 22:01:56,733 - INFO - [logger.py:26] - Bar diagram created
2025-07-13 20:49:54,372 - INFO - [logger.py:26] - Visualize initialized
2025-07-13 20:49:54,872 - INFO - [category.py:224] - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2025-07-13 20:49:54,875 - INFO - [category.py:224] - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2025-07-13 20:49:56,728 - INFO - [logger.py:26] - plot diagram created
2025-07-13 20:49:58,702 - INFO - [logger.py:26] - Bar diagram created
2025-07-13 20:50:00,915 - INFO - [logger.py:26] - Boxplot diagram created
2025-07-13 20:50:01,165 - INFO - [logger.py:26] - Pie diagram created
